// list all endpoints
export const __tags: any = {
    "https://nekos.life/api/v2/img/": [
        "tickle",
        "slap",
        "poke",
        "pat",
        "neko",
        "meow",
        "kiss",
        "hug",
        "feed",
        "cuddle",
        "kemonomimi",
        "holo",
        "smug",
        "baka",
        "wallpaper",
        "goose",
        "gecg",
        "avatar",
        "waifu",
    ],
    "http://api.nekos.fun:8080/api/": [
        "kiss",
        "lick",
        "baka",
        "hug",
        "cry",
        "poke",
        "smug",
        "slap",
        "tickle",
        "pat",
        "laugh",
        "feed",
        "cuddle",
    ],
};
